on: push

name: Continuous integration (Generation code)

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      # Generation code
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --manifest-path iban_validate_registry_generation/Cargo.toml

      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path iban_validate_registry_generation/Cargo.toml
