on: push

name: Continuous integration

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          components: rustfmt, clippy

      # Default features
      - uses: actions-rs/cargo@v1
        with:
          command: build --manifest-path iban_validate/Cargo.toml

      - uses: actions-rs/cargo@v1
        with:
          command: test --manifest-path iban_validate/Cargo.toml

      - uses: actions-rs/cargo@v1
        with:
          command: doc --manifest-path iban_validate/Cargo.toml

      # No features
      - uses: actions-rs/cargo@v1
        with:
          command: build --no-default-features --manifest-path iban_validate/Cargo.toml

      - uses: actions-rs/cargo@v1
        with:
          command: test --no-default-features --manifest-path iban_validate/Cargo.toml

      - uses: actions-rs/cargo@v1
        with:
          command: doc --no-default-features --manifest-path iban_validate/Cargo.toml

      # Serde
      - uses: actions-rs/cargo@v1
        with:
          command: build --no-default-features --features serde --manifest-path iban_validate/Cargo.toml

      - uses: actions-rs/cargo@v1
        with:
          command: test --no-default-features --features serde --manifest-path iban_validate/Cargo.toml

      - uses: actions-rs/cargo@v1
        with:
          command: doc --no-default-features --features serde --manifest-path iban_validate/Cargo.toml

      # All features
      - uses: actions-rs/cargo@v1
        with:
          command: build --features serde --manifest-path iban_validate/Cargo.toml

      - uses: actions-rs/cargo@v1
        with:
          command: test --features serde --manifest-path iban_validate/Cargo.toml

      - uses: actions-rs/cargo@v1
        with:
          command: doc --features serde --manifest-path iban_validate/Cargo.toml

      # Generation code
      - uses: actions-rs/cargo@v1
        with:
          command: build --manifest-path iban_validate_registry_generation/Cargo.toml

      - uses: actions-rs/cargo@v1
        with:
          command: test --manifest-path iban_validate_registry_generation/Cargo.toml

      # Clippy & Fmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
